config/routes.rb
Training::Application.routes.draw do
  resources :contents

  resources :courses

  resources :tags

  devise_for :users
  get "home/index"
    get "home/index2"
  root "home#index"

end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :course
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :courses
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
    protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :country, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :perfil, :ciudad, :phone, :twitter, :facebook, :about, :info, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render action: 'show', status: :created, location: @content }
      else
        format.html { render action: 'new' }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:title, :description, :course_id, :video, :archivos)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title, :descrition, :level, :tag_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :authenticate_user! 
  def index
  	    @tags = Tag.all
  end
  def index2
  	
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tag }
      else
        format.html { render action: 'new' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/contents/_form.html.erb
<%= simple_form_for(@content) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.association :course %>
    <%= f.input :video %>
    <%= f.input :archivos %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing content</h1>

<%= render 'form' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<h1>Listing contents</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Course</th>
      <th>Video</th>
      <th>Archivos</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= content.title %></td>
        <td><%= content.description %></td>
        <td><%= content.course %></td>
        <td><%= content.video %></td>
        <td><%= content.archivos %></td>
        <td><%= link_to 'Show', content %></td>
        <td><%= link_to 'Edit', edit_content_path(content) %></td>
        <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>New content</h1>

<%= render 'form' %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @content.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @content.description %>
</p>

<p>
  <strong>Course:</strong>
  <%= @content.course %>
</p>

<p>
  <strong>Video:</strong>
  <%= @content.video %>
</p>

<p>
  <strong>Archivos:</strong>
  <%= @content.archivos %>
</p>

<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>

app/views/courses/_form.html.erb
<%= simple_form_for(@course) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :descrition %>
    <%= f.input :level %>
    <%= f.association :tag %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Descrition</th>
      <th>Level</th>
      <th>Tag</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= course.descrition %></td>
        <td><%= course.level %></td>
        <td><%= course.tag %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>

<p>
  <strong>Descrition:</strong>
  <%= @course.descrition %>
</p>

<p>
  <strong>Level:</strong>
  <%= @course.level %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @course.tag %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/home/index.html.erb
<header class="header bg-white b-b b-light">
<p>
	John's profile
</p>
</header>

app/views/home/video.html.erb
<!DOCTYPE html><html lang="en" class="app">
<head>
<meta charset="utf-8"/>
<title>aclase | lubu training</title>
<meta name="description" content="app, web app, responsive, admin dashboard, admin, flat, flat ui, ui kit, off screen nav"/>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
<link rel="stylesheet" href="../css/app.v2.css" type="text/css"/>
<link rel="stylesheet" href="../css/font.css" type="text/css" cache="false"/>
<!--[if lt IE 9]> <script src="js/ie/html5shiv.js" cache="false"></script> <script src="js/ie/respond.min.js" cache="false"></script> <script src="js/ie/excanvas.js" cache="false"></script> <![endif]-->
</head>
<body>
<section class="vbox">
	<!--inicio header -->
<%= render 'shared/header'%>
	<!-- fin header -->
<section><section class="hbox stretch">
<!-- .aside -->
<%= render 'shared/nav'%>
<!-- /.aside -->
<section id="content">
	<section class="vbox">

<section class="scrollable">
	<section class="hbox stretch">

<aside class="bg-white"><section class="vbox"><section class="scrollable">
<!--formulario-->
<form data-validate="parsley">
	<section class="panel panel-default"><header class="panel-heading"><span class="h4">Actualizar</span></header>
	<div class="panel-body">
		<p class="text-muted">
			Por favor, complete la información para continuar
		</p>
		<div class="form-group">
			<label>nombre</label><input type="text" class="form-control parsley-validated" data-required="true">
		</div>
		<div class="form-group">
			<label>Email</label><input type="text" class="form-control parsley-validated" data-type="email" data-required="true">
		</div>
		<div class="form-group pull-in clearfix">
			<div class="col-sm-6">
				<label>Enter password</label><input type="password" class="form-control parsley-validated" data-required="true" id="pwd">
			</div>
			<div class="col-sm-6">
				<label>Confirm password</label><input type="password" class="form-control parsley-validated" data-equalto="#pwd" data-required="true">
			</div>
		</div>
		<div class="form-group">
			<label>Ciudad</label><input type="text" class="form-control parsley-validated" data-type="phone" placeholder="(XXX) XXXX XXX" data-required="true">
		</div>
		<div class="form-group">
			<label>Phone</label><input type="text" class="form-control parsley-validated" data-type="phone" placeholder="(XXX) XXXX XXX" data-required="true">
		</div>
		<div class="form-group">
			<label>Perfil</label>
			<select data-required="true" class="form-control m-t parsley-validated"> <option value="">Please choose</option> <option value="foo">Foo</option> <option value="bar">Bar</option> </select>
		</div>
		<div class="form-group"> 
			<label>información</label> <textarea class="form-control parsley-validated" rows="6" data-minwords="6" data-required="true" placeholder="Type your message"></textarea> 
		</div>
		
		
		<div class="checkbox">
			<label><input type="checkbox" name="check" checked="" data-required="true" class="parsley-validated"> I agree to the <a href="#" class="text-info">Terms of Service</a></label>
		</div>
	</div>
	<footer class="panel-footer text-right bg-light lter"><button type="submit" class="btn btn-success btn-s-xs">Submit</button></footer></section>
</form>
<!--finaliza formulario-->
</section></section></aside><aside class="col-lg-4 b-l "><section class="vbox"><section class="scrollable">
<section class="panel panel-default" id="progressbar"> <header class="panel-heading"><span class="h4">Progreso</span></header>
<ul class="list-group">
	<li class="list-group-item">
		<strong>ruby</strong>
		<div class="progress progress-sm m-t-sm"> 

			<div class="progress-bar progress-bar-info" data-toggle="tooltip" data-original-title="95%" style="width: 95%;"></div> 
		</div>
	</li>
	<li class="list-group-item">
		<strong>sql</strong>
		<div class="progress progress-sm m-t-sm"> 

			<div class="progress-bar progress-bar-warning" data-toggle="tooltip" data-original-title="95%" style="width: 95%;"></div> 
		</div>
	</li>
</ul>
</section>
</section></section></aside></section></section></section><a href="#" class="hide nav-off-screen-block" data-toggle="class:nav-off-screen" data-target="#nav"></a></section><aside class="bg-light lter b-l aside-md hide" id="notes">
<div class="wrapper">
	Notification
</div>
</aside></section></section></section>
<script src="../js/app.v2.js"></script>
<!-- Bootstrap -->
<!-- App -->
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es" class="app">
<head>
  <title>aclases</title>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="../css/app.v2.css" type="text/css"/>
  <link rel="stylesheet" href="../css/font.css" type="text/css" cache="false"/>
  <!--[if lt IE 9]> <script src="js/ie/html5shiv.js" cache="false"></script> <script src="js/ie/respond.min.js" cache="false"></script> <script src="js/ie/excanvas.js" cache="false"></script> <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>
  <section class="vbox">
    <!--inicio header -->
<%= render 'shared/header'%>
  <!-- fin header -->
<section>
  <section class="hbox stretch">
<!-- .aside -->
<%= render 'shared/nav'%>
<!-- /.aside -->
<section id="content">
  <section class="vbox">

<%= yield %>

</section>
</section>
</section>
</section>
</section>
<!--script-->
<script src="../js/app.v2.js"></script>
</body>
</html>

app/views/shared/_header.html.erb
<header class="bg-dark dk header navbar navbar-fixed-top-xs">
<div class="navbar-header aside-md">
	<a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen" data-target="#nav"><i class="fa fa-bars"></i></a><a href="#" class="navbar-brand" data-toggle="fullscreen"><img src="../images/logo.png" class="m-r-sm">aclase</a><a class="btn btn-link visible-xs" data-toggle="dropdown" data-target=".nav-user"><i class="fa fa-cog"></i></a>
</div>
<ul class="nav navbar-nav hidden-xs">
	<!--
	<li class="dropdown"><a href="#" class="dropdown-toggle dker" data-toggle="dropdown"><i class="fa fa-building-o"></i><span class="font-bold">Activity</span></a><section class="dropdown-menu aside-xl on animated fadeInLeft no-borders lt">
	<div class="wrapper lter m-t-n-xs">
		<a href="#" class="thumb pull-left m-r"><img src="../images/avatar.jpg" class="img-circle"></a>
		<div class="clear">
			<a href="#"><span class="text-white font-bold">@Mike Mcalidek</a></span><small class="block">Art Director</small><a href="#" class="btn btn-xs btn-success m-t-xs">Upgrade</a>
		</div>
	</div>
	<div class="row m-l-none m-r-none m-b-n-xs text-center">
		<div class="col-xs-4">
			<div class="padder-v">
				<span class="m-b-xs h4 block text-white">245</span><small class="text-muted">Followers</small>
			</div>
		</div>
		<div class="col-xs-4 dk">
			<div class="padder-v">
				<span class="m-b-xs h4 block text-white">55</span><small class="text-muted">Likes</small>
			</div>
		</div>
		<div class="col-xs-4">
			<div class="padder-v">
				<span class="m-b-xs h4 block text-white">2,035</span><small class="text-muted">Photos</small>
			</div>
		</div>
	</div>
	</section></li> actividad y ungadear la cuenta -->
	<!--<li>
	<div class="m-t m-l">
		<a href="price.html" class="dropdown-toggle btn btn-xs btn-primary" title="Upgrade"><i class="fa fa-long-arrow-up"></i></a>
	</div>
	</li> precios para upgradear la cuenta -->
</ul>
<ul class="nav navbar-nav navbar-right hidden-xs nav-user">
	<li class="hidden-xs"><a href="#" class="dropdown-toggle dk" data-toggle="dropdown"><i class="fa fa-bell"></i><span class="badge badge-sm up bg-danger m-l-n-sm count">2</span></a><section class="dropdown-menu aside-xl"><section class="panel bg-white"><header class="panel-heading b-light bg-light"><strong>You have <span class="count">2</span> notifications</strong></header>
	<div class="list-group list-group-alt animated fadeInRight">
		<a href="#" class="media list-group-item"><span class="pull-left thumb-sm"><img src="../images/avatar.jpg" alt="John said" class="img-circle"></span><span class="media-body block m-b-none"> Use awesome animate.css<br>
		<small class="text-muted">10 minutes ago</small></span></a><a href="#" class="media list-group-item"><span class="media-body block m-b-none"> 1.0 initial released<br>
		<small class="text-muted">1 hour ago</small></span></a>
	</div>
	<footer class="panel-footer text-sm"><a href="#" class="pull-right"><i class="fa fa-cog"></i></a><a href="#notes" data-toggle="class:show animated fadeInRight">See all the notifications</a></footer></section></section></li>
		<!--
	<li class="dropdown hidden-xs"><a href="#" class="dropdown-toggle dker" data-toggle="dropdown"><i class="fa fa-fw fa-search"></i></a>
		<section class="dropdown-menu aside-xl animated fadeInUp"><section class="panel bg-white">

	<form role="search">
		<div class="form-group wrapper m-b-none">
			<div class="input-group">
				<input type="text" class="form-control" placeholder="Search"><span class="input-group-btn"><button type="submit" class="btn btn-info btn-icon"><i class="fa fa-search"></i></button></span>
			</div>
		</div>
	</form> 
	</section></section></li>-->
	<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="thumb-sm avatar pull-left"><img src="../images/avatar.jpg"></span> <%= current_user.name %> <b class="caret"></b></a>
	<ul class="dropdown-menu animated fadeInRight">
		<span class="arrow top"></span>
		<li>
		 <%= link_to edit_user_registration_path do %>
		 Perfil
		 <% end %> 
		</li>
		 
		<!--<li><a href="#"><span class="badge bg-danger pull-right">3</span> Notifications </a></li>-->
		<!--<li><a href="docs.html">Help</a></li>-->
		<li class="divider"></li>
			 <li>
			 	<%= link_to(destroy_user_session_path, :method => :delete, :data => {:toggle=>"ajaxModal"}) do %>
                  Salir
                  <% end %>
			 </li> 
		<!--<li><a href="modal.lockme.html" data-toggle="">Logout</a></li>-->
	</ul>
	</li>
</ul>
</header>

app/views/tags/_form.html.erb
<%= simple_form_for(@tag) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<header class="header bg-white b-b b-light">
<p>
  John's profile
</p>
</header>


<h1>Listing tags</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.title %></td>
        <td><%= tag.description %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<header class="header bg-white b-b b-light">
	<p><%= @tag.title %></p>
</header>
<section class="scrollable wrapper">
	<p id="notice"><%= notice %></p>
	<div class="row"><!-- inicio columnas prinicipal-->
			<% @tag.courses.each do |course| %>
		<div class="col-sm-6 col-md-4"><!-- inicio columnas-->
        <div class="thumbnail"><!-- inicia thumbnail-->
        	<section class="panel panel-info"> 
        		<div class="panel-body"> 
        			<a href="#" class="thumb pull-right m-l"> <img src="../images/avatar.jpg" class="img-circle"> </a> 
        			<label class=" pull-right label label-warning"><%= course.level%></label>
        			<div class="clear">
        				<%= link_to  course do %>
        				<span class="text-info" ><%= course.title %></span><br>
        				<%end%>
        				<div>
        					<br>
        				<small class="block text-muted"><%= course.descrition%></small> 
        				</div>
        				 <br>
        				<%= link_to "ingresar",  course, :class => 'btn btn-xs btn-success m-t-xs' %>
        			</div> 
        		</div>
        	</section>
        	<%= link_to 'Editar', edit_tag_path(@tag) %> |
			<%= link_to 'Atras', tags_path %>
        </div><!-- finaliza thumbnail-->
      </div> <!-- finaliza columnas-->
      <% end %>
    </div><!-- finaliza columnas prinicipal-->
</section>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>